### ISSUE TITLE
Will not cooperate with Netezza driver

### ISSUE THREAD

**Issue by snhirsch** [CartoDB/odbc_fdw#34] opened 2016-08-25 19:52 UTC
I have tried everything I can think of, but cannot get this driver to connect with a Netezza database.  I rebuilt with debugging (you are missing the include of a critical header for that, BTW) and the connection string looks reasonable.  I'm starting to suspect a dynamic load problem.  How exactly does the PostgreSQL runtime locate the driver manager?  Is it precompiled for any particular one?  

I'd be glad to roll up my sleeves and debug this further if you can suggest how to attach it with a debugger.

Update: Figured it out...  The Netezza driver has a dependency on other shared libraries in its directory.  It's necessary to set LD_LIBRARY_PATH for the postgres user and restart the database in order to get things cooperating.

Next Problem:  It returns only empty rows from foreign queries (although the correct number of such rows).

**Comment by jgoizueta** [comment] 2016-08-29 16:18
If you recompile the code having defined DEBUG (i.e. `make DEBUG=1`), and then change the message level in the database with `set client_min_messages to 'debug';` (I assume you're using `psql`) you'll get all the debug messages in the console. You also will get debug symbols in the executables (.so) to be used by a debugger. I'm not aware of any missing header, so I'll be glad if you give us any further information about that.

Then, as a simple way a finding about the problem you could setup additional debug comments in the code with `elog(DEBUG1, ...)`.

If that's not enough to find out what the problem is you can use a debugger such as `gdb`. The problem is, unless you have postgres recompiled for debugging, you won't have postgres debug symbols, so you'll be able to debug the extension code but not follow it into progres source code.

But using a debugger with symbols only for odbd_fdw could be enough for your purposes. To attach `gdb` to PostgreSQL you must first find your backend process id by executing the SQL command: `SELECT * FROM pg_backend_pid;`and then using that PID with `sudo gdb -p PID`. 

From `gdb` you could set breakpoints in the odbc_fdw extension code, for example:
```
b odbcBeginForeignScan
``` 
(and then you have to continue the execution of postgres with the command `c`).

You can find additional information [here](https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD)

I hope this helps you start debugging your problems with Netezza and you share your findings here.

**Comment by jgoizueta** [comment] 2016-08-29 16:30
\<off-topic>
Hey @snhirsch I just saw your mustang-midi-bridge project! I have a Mustang II, so I'll be looking it to it. It really looks good!
\</off-topic>

**Comment by snhirsch** [comment] 2016-08-29 16:49
I updated my original post to indicate the root cause of the problem, but it's worth restating for clarity:

The Netezza ODBC driver relies on several other shared libraries in the same directory.  Solution is to add the appropriate statement to /var/lib/pgsql/.bash_profile and restart PG from a new login session (to ensure that the setting is effective):
```
export LD_LIBRARY_PATH=/usr/pgsql-9.1/lib:$LD_LIBRARY_PATH
```

**Comment by snhirsch** [comment] 2016-08-29 16:51
@jgoizueta   Thanks for the comment on the mustang-midi-bridge!  There may be some rough edges with Mustang I or II, since they are slightly different and I don't have access to either.  Open an issue on my GitHub page and I'll be glad to work with you.

**Comment by snhirsch** [comment] 2016-08-31 15:36
When importing from Netezza, I end up fighting with the case of column names.  NZ reports them in upper case, and pgSQL does not treat that in a case-insensitive manner.  I have to alias absolutely everything in my 'sql_query' option which is a royal pain.  The wrapper could really use an option to force all imported identifiers to lower case.

**Comment by rafatower** [comment] 2016-11-21 12:24
Closing this as the original issue is solved. Feel free to open a different one with your suggestions for the case sensitive column names issue you faced

**Closed by rafatower** 2016-11-21 12:24 UTC
