### ISSUE TITLE
Fix continuous integration builds

### ISSUE THREAD

**Issue by rafatower** [CartoDB/odbc_fdw#65] opened 2017-12-22 12:03 UTC
Our travis builds seem to be broken.

E.g:

```
$ openssl aes-256-cbc -K $encrypted_d52b986e6313_key -iv $encrypted_d52b986e6313_iv -in $TRAVIS_BUILD_DIR/test/config/hive.config.enc -out $TRAVIS_BUILD_DIR/test/config/hive.config -d
iv undefined
The command "openssl aes-256-cbc -K $encrypted_d52b986e6313_key -iv $encrypted_d52b986e6313_iv -in $TRAVIS_BUILD_DIR/test/config/hive.config.enc -out $TRAVIS_BUILD_DIR/test/config/hive.config -d" failed and exited with 1 during .
Your build has been stopped.
```

https://travis-ci.org/CartoDB/odbc_fdw/builds/311008753?utm_source=github_status&utm_medium=notification

**Comment by rafatower** [comment] 2018-02-06 16:53
IIRC @jgoizueta and @ethervoid set up the CI at the time with some help from @CartoDB/systems 

Here's a branch with an attempt at fixing CI: https://github.com/CartoDB/odbc_fdw/pull/67

Tests get stuck mid-way. I'd suspect of some infrastructure issue while trying to connect to a foreign database. Can anyone involved and/or with visibility on the problem lend a hand here?

PS: consider moving this to a private repo, since this seems to be about infrastructure and private resources management.

**Comment by jgoizueta** [comment] 2018-02-06 17:58
I have the credentials for which I believe are the MySQL and SQL Server RDS used and they still work, but I don't have those of Hive and Postgresql. I think @ethervoid set those (do you by any chance still have  around the config files or the clear-text travis keys?)

**Comment by ethervoid** [comment] 2018-02-06 18:07
I think so on my laptop. I'm doing some tests and I've asked Travis to [enable the debug mode](https://docs.travis-ci.com/user/running-build-in-debug-mode/) for that project in order to be able to connect to it using ssh

**Comment by ethervoid** [comment] 2018-02-06 18:13
I've checked and I have them. The only one is going to connect outside is the SQL Server one, the rest I move it inside Travis in order to avoid connecting to external services. If you need them I can provide them by Slack

**Comment by ethervoid** [comment] 2018-02-06 19:06
We're now able to enter the machine using ssh. To do it you have to follow [these instructions](https://docs.travis-ci.com/user/running-build-in-debug-mode/#Restarting-a-job-in-debug-mode-via-API)

I've done some checks and it seems it gets stuck trying to connect using odbc:

I've checked the FDW configuration and it seems to be correct
```sql
postgres=# \c contrib_regression 
You are now connected to database "contrib_regression" as user "postgres".
contrib_regression=# select * from pg_foreign_
pg_foreign_data_wrapper pg_foreign_server       pg_foreign_table       
contrib_regression=# select * from pg_foreign_
pg_foreign_data_wrapper pg_foreign_server       pg_foreign_table       
contrib_regression=# select * from pg_foreign_server 
contrib_regression-# ;
   srvname    | srvowner | srvfdw | srvtype | srvversion | srvacl |                                             srvoptions                                             
--------------+----------+--------+---------+------------+--------+----------------------------------------------------------------------------------------------------
 hive_fdw     |       10 |  16408 |         |            |        | {"odbc_driver=Hortonworks Hive ODBC Driver 64-bit",odbc_host=localhost,odbc_port=10000}
 mysql_fdw    |       10 |  16408 |         |            |        | {odbc_driver=MySQL,odbc_server=localhost,odbc_port=3306,odbc_database=fdw_tests,encoding=iso88591}
 postgres_fdw |       10 |  16408 |         |            |        | {"odbc_driver=PostgreSQL Unicode",odbc_server=localhost,odbc_port=5432,odbc_database=fdw_tests}
(3 rows)

contrib_regression=# select * from pg_foreign_table;
 ftrelid | ftserver | ftoptions 
---------+----------+-----------
(0 rows)

contrib_regression=# select * from pg_foreign_data_wrapper ;
 fdwname  | fdwowner | fdwhandler | fdwvalidator | fdwacl | fdwoptions 
----------+----------+------------+--------------+--------+------------
 odbc_fdw |       10 |      16406 |        16407 |        | 
(1 row)

contrib_regression=# select * from pg_user_mapping;
 umuser | umserver |           umoptions           
--------+----------+-------------------------------
     10 |    16415 | 
     10 |    16417 | {odbc_uid=root,odbc_pwd=}
     10 |    16419 | {odbc_uid=postgres,odbc_pwd=}
(3 rows)
```
but the `IMPORT FOREIGN SCHEMA` get stuck:
```bash
The command "make integration_tests || { cat test/regression.diffs; false; }" exited with 1.
travis@travis-job-8be57969-3677-4b69-a9ad-e29c64fc0c9e:~/build/CartoDB/odbc_fdw$ ps aux | grep postgres
postgres  8335  0.0  0.2 260824 21864 ?        S    18:56   0:00 /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -c config_file=/etc/postgresql/9.5/main/postgresql.conf
postgres  8337  0.0  0.0 260948  6140 ?        Ss   18:56   0:00 postgres: 9.5/main: checkpointer process                                                                                    
postgres  8338  0.0  0.0 260824  5176 ?        Ss   18:56   0:00 postgres: 9.5/main: writer process                                                                                          
postgres  8339  0.0  0.0 260824  3608 ?        Ss   18:56   0:00 postgres: 9.5/main: wal writer process                                                                                      
postgres  8340  0.0  0.0 261244  6028 ?        Ss   18:56   0:00 postgres: 9.5/main: autovacuum launcher process                                                                             
postgres  8341  0.0  0.0 115964  3872 ?        Ss   18:56   0:00 postgres: 9.5/main: stats collector process                                                                                 
travis    9313  0.0  0.0 110564  6760 pts/1    S    19:00   0:00 /usr/lib/postgresql/9.5/bin/psql -X -a -q -d contrib_regression
postgres  9314  0.0  0.1 283944 14920 ?        Ss   19:00   0:00 postgres: 9.5/main: postgres contrib_regression [local] IMPORT FOREIGN SCHEMA                                               
postgres  9315  0.0  0.1 261780 10604 ?        Ss   19:00   0:00 postgres: 9.5/main: postgres fdw_tests 127.0.0.1(42770) idle                                                                
travis    9357  0.0  0.0  21284  2304 pts/1    S+   19:00   0:00 grep postgres
```

Also I've removed all the instances of postgres and reinstall 9.5 to avoid problems. The `pg_hba.conf` file is fine too:
```
travis@travis-job-8be57969-3677-4b69-a9ad-e29c64fc0c9e:~/build/CartoDB/odbc_fdw$ sudo cat /etc/postgresql/9.5/main/pg_hba.conf 
# TYPE  DATABASE        USER            ADDRESS                 METHOD 
local   all             postgres                                trust
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
```

and the `postgresql.conf` too.

Tomorrow I'll try to do more tests

**Comment by ethervoid** [comment] 2018-02-07 11:30
There is something weird. I've been doing the operation manually and using strace for it. First time I try to import a foreign schema we get:
```
connect(81, {sa_family=AF_INET, sin_port=htons(5432), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=81, events=POLLOUT|POLLERR}], 1, 4294967295) = 1 ([{fd=81, revents=POLLOUT}])
getsockopt(81, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
getsockname(81, {sa_family=AF_INET, sin_port=htons(43476), sin_addr=inet_addr("127.0.0.1")}, [16]) = 0
poll([{fd=81, events=POLLOUT|POLLERR}], 1, 4294967295) = 1 ([{fd=81, revents=POLLOUT}])
sendto(81, "\0\0\0*\0\3\0\0user\0postgres\0database\0f"..., 42, MSG_NOSIGNAL, NULL, 0) = 42
poll([{fd=81, events=POLLIN|POLLERR}], 1, 4294967295) = 1 ([{fd=81, revents=POLLIN}])
recvfrom(81, "R\0\0\0\10\0\0\0\0S\0\0\0\26application_name\0\0"..., 16384, 0, NULL, NULL) = 319
sendto(81, "Q\0\0\0PSET DateStyle = 'ISO';SET e"..., 81, MSG_NOSIGNAL, NULL, 0) = 81
poll([{fd=81, events=POLLIN|POLLERR}], 1, 4294967295) = 1 ([{fd=81, revents=POLLIN}])
recvfrom(81, "S\0\0\0\27DateStyle\0ISO, MDY\0C\0\0\0\10SET"..., 16384, 0, NULL, NULL) = 130
sendto(81, "Q\0\0\0>select oid, typbasetype fro"..., 63, MSG_NOSIGNAL, NULL, 0) = 63
poll([{fd=81, events=POLLIN|POLLERR}], 1, 4294967295) = 1 ([{fd=81, revents=POLLIN}])
recvfrom(81, "T\0\0\0:\0\2oid\0\0\0\4\337\377\376\0\0\0\32\0\4\377\377\377\377\0\0typ"..., 16384, 0, NULL, NULL) = 79
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
write(2, "2018-02-07 11:28:24.792 UTC [966"..., 347) = 347
sendto(10, "E\0\0\0QSERROR\0C42622\0Mencoding nam"..., 82, 0, NULL, 0) = 82
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
sendto(9, "\2\0\0\0\350\1\0\0\24@\0\0\4\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 488, 0, NULL, 0) = 488
sendto(10, "Z\0\0\0\5I", 6, 0, NULL, 0) = 6
recvfrom(10, 0x556b396743c0, 8192, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
read(11, 0x7ffc04805430, 16)            = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=10, events=POLLIN}, {fd=11, events=POLLIN}], 2, 4294967295
```

and the error message: **ERROR:  encoding name too long**

then the second try hungs the session:
```
recvfrom(10, "Q\0\0\0\301IMPORT FOREIGN SCHEMA publi"..., 8192, 0, NULL, NULL) = 194
access("/etc/odbc.ini", F_OK)           = 0
stat("/etc/odbc.ini", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
semget(0x79012f2c, 1, IPC_CREAT|IPC_EXCL|0666) = -1 EEXIST (File exists)
semget(0x79012f2c, 1, IPC_CREAT|0666)   = 6094856
shmget(0x79012f2c, 808, IPC_CREAT|IPC_EXCL|0666) = -1 EEXIST (File exists)
shmget(0x79012f2c, 808, 0666)           = 688129
shmat(688129, 0, 0)                     = 0x7fe1011ac000
semop(6094856, {{0, 0, 0}, {0, 1, SEM_UNDO}}, 2) = 0
semop(6094856, {{0, -1, SEM_UNDO}}, 1)  = 0
semop(6094856, {{0, 0, 0}, {0, 1, SEM_UNDO}}, 2) = 0
semop(6094856, {{0, -1, SEM_UNDO}}, 1)  = 0
futex(0x7fe0f1614480, FUTEX_WAIT_PRIVATE, 2, NULL
```

**Comment by ethervoid** [comment] 2018-02-07 11:39
I've augmented the column size for strace to gather the maximum number of characters:

```
recvfrom(33, "R\0\0\0\10\0\0\0\0S\0\0\0\26application_name\0\0S\0\0\0\31client_encoding\0UTF8\0S\0\0\0\27DateStyle\0ISO, MDY\0S\0\0\0\31integer_datetimes\0on\0S\0\0\0\33IntervalStyle\0postgres\0S\0\0\0\24is_superuser\0on\0S\0\0\0\31server_encoding\0UTF8\0S\0\0\0\32server_version\0009.5.10\0S\0\0\0#session_authorization\0postgres\0S\0\0\0#standard_conforming_strings\0on\0S\0\0\0\21TimeZone\0UTC\0K\0\0\0\f\0\0*\241H\304\17\352Z\0\0\0\5I", 16384, 0, NULL, NULL) = 319
sendto(33, "Q\0\0\0PSET DateStyle = 'ISO';SET extra_float_digits = 2;show transaction_isolation\0", 81, MSG_NOSIGNAL, NULL, 0) = 81
poll([{fd=33, events=POLLIN|POLLERR}], 1, 4294967295) = 1 ([{fd=33, revents=POLLIN}])
recvfrom(33, "S\0\0\0\27DateStyle\0ISO, MDY\0C\0\0\0\10SET\0C\0\0\0\10SET\0T\0\0\0.\0\1transaction_isolation\0\0\0\0\0\0\0\0\0\0\31\377\377\377\377\377\377\0\0D\0\0\0\30\0\1\0\0\0\16read committedC\0\0\0\tSHOW\0Z\0\0\0\5I", 16384, 0, NULL, NULL) = 130
sendto(33, "Q\0\0\0>select oid, typbasetype from pg_type where typname = 'lo'\0", 63, MSG_NOSIGNAL, NULL, 0) = 63
poll([{fd=33, events=POLLIN|POLLERR}], 1, 4294967295) = 1 ([{fd=33, revents=POLLIN}])
recvfrom(33, "T\0\0\0:\0\2oid\0\0\0\4\337\377\376\0\0\0\32\0\4\377\377\377\377\0\0typbasetype\0\0\0\4\337\0\30\0\0\0\32\0\4\377\377\377\377\0\0C\0\0\0\rSELECT 0\0Z\0\0\0\5I", 16384, 0, NULL, NULL) = 79
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
write(2, "2018-02-07 11:35:07.750 UTC [10711] postgres@source_db ERROR:  encoding name too long\n2018-02-07 11:35:07.750 UTC [10711] postgres@source_db STATEMENT:  IMPORT FOREIGN SCHEMA public\n\t    FROM SERVER postgres_fdw\n\t    INTO public\n\t    OPTIONS(\n\t      table 'postgres_test_table',\n\t      odbc_BoolsAsChar '0',\n\t      odbc_ByteaAsLongVarBinary '1'\n\t);\n", 349) = 349
sendto(10, "E\0\0\0QSERROR\0C42622\0Mencoding name too long\0Fencnames.c\0L496\0Rpg_char_to_encoding\0\0", 82, 0, NULL, 0) = 82
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
sendto(9, "\2\0\0\0\250\3\0\0\24@\0\0\10\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\213\r\0\0\202U\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\211\5\0\0\377\177\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0%\2\0\0\377\177\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0q\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0007\n\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0|\n\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\30\t\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0p\0\0\0\202U\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 936, 0, NULL, 0) = 936
sendto(9, "\2\0\0\0\350\1\0\0\24@\0\0\4\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\347\4\0\0\202U\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\202\n\0\0\377\177\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\212\5\0\0\377\177\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\257\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 488, 0, NULL, 0) = 488
sendto(10, "Z\0\0\0\5I", 6, 0, NULL, 0) = 6
```

Here we can see something interesting: ` "E\0\0\0QSERROR\0C42622\0Mencoding name too long\0Fencnames.c\0L496\0Rpg_char_to_encoding\0\0"`

Keep diggin'

**Comment by jgoizueta** [comment] 2018-02-07 12:06
Wow, great findings @ethervoid, good work!

Are you setting the `encoding` env variable in the config files?
The MySQl test seems the only one using it: https://github.com/CartoDB/odbc_fdw/blob/master/test/template/mysql_installation_test.tpl#L8

**Comment by ethervoid** [comment] 2018-02-07 12:11
Yes, I'm sending it in my tests by it seems to be ignored or that is not the culprit. I think the error comes from [here](https://github.com/CartoDB/odbc_fdw/blob/master/odbc_fdw.c#L1376)

I'm going to create a new local virtual machine with that version of Postgres and try to use gdb to follow the rabbit through the rabbit hole

**Comment by ethervoid** [comment] 2018-02-07 13:33
This is the trace from my local virtual machine that is working perfectly:

```poll([{fd=32, events=POLLIN}], 1, -1)   = 1 ([{fd=32, revents=POLLIN}])
recvfrom(32, "R\0\0\0\10\0\0\0\0S\0\0\0\26application_name\0\0S\0\0\0\31client_encoding\0UTF8\0S\0\0\0\27DateStyle\0ISO, MDY\0S\0\0\0\31integer_datetimes\0on\0S\0\0\0\33IntervalStyle\0postgres\0S\0\0\0\24is_superuser\0on\0S\0\0\0\3$
server_encoding\0UTF8\0S\0\0\0\32server_version\0009.5.10\0S\0\0\0#session_authorization\0postgres\0S\0\0\0#standard_conforming_strings\0on\0S\0\0\0\21TimeZone\0UTC\0K\0\0\0\f\0\0001|8}\1jZ\0\0\0\5I", 4096, MSG_NOSIGNAL, NULL, NULL$
 = 319
write(24, "    [ PostgreSQL version string = '9.5.10' ]\n", 45) = 45
write(24, "    [ PostgreSQL version number = '9.5' ]\n", 42) = 42
write(24, "conn=0x55cecb52eb70, query='select oid, typbasetype from pg_type where typname = 'lo''\n", 87) = 87
sendto(32, "Q\0\0\0>select oid, typbasetype from pg_type where typname = 'lo'\0", 63, MSG_NOSIGNAL, NULL, 0) = 63
recvfrom(32, 0x55cecb52cb00, 4096, MSG_NOSIGNAL, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=32, events=POLLIN}], 1, -1)   = 1 ([{fd=32, revents=POLLIN}])
recvfrom(32, "T\0\0\0:\0\2oid\0\0\0\4\337\377\376\0\0\0\32\0\4\377\377\377\377\0\0typbasetype\0\0\0\4\337\0\30\0\0\0\32\0\4\377\377\377\377\0\0C\0\0\0\rSELECT 0\0Z\0\0\0\5I", 4096, MSG_NOSIGNAL, NULL, NULL) = 79
write(24, "    [ fetched 0 rows ]\n", 23) = 23
write(24, "    [ Large Object oid = -999 ]\n", 32) = 32
write(24, "    [ Client encoding = 'UTF8' (code = 6) ]\n", 44) = 44
write(24, "conn=0x55cecb52eb70, PGAPI_DriverConnect(out)='DRIVER=PostgreSQL Unicode;DATABASE=fdw_tests;SERVER=localhost;PORT=5432;UID=postgres;PWD=;SSLmode=disable;ReadOnly=0;Protocol=7.4;FakeOidIndex=0;ShowOidColumn=0;RowVersionin$
=0;ShowSystemTables=0;ConnSettings=;Fetch=100;Socket=4096;UnknownSizes=0;MaxVarcharSize=255;MaxLongVarcharSize=8190;Debug=0;CommLog=1;Optimizer=0;Ksqo=1;UseDeclareFetch=0;TextAsLongVarchar=1;UnknownsAsLongVarchar=0;BoolsAsChar=0;Pa$
se=0;CancelAsFreeStmt=0;ExtraSysTablePrefixes=dd_;;LFConversion=0;UpdatableCursors=1;DisallowPremature=0;TrueIsMinus1=0;BI=0;ByteaAsLongVarBinary=1;UseServerSidePrepare=1;LowerCaseIdentifier=0;'\n", 648) = 648
write(24, "conn=0x55cecb52eb70, query='select n.nspname, c.relname, a.attname, a.atttypid, t.typname, a.attnum, a.attlen, a.atttypmod, a.attnotnull, c.relhasrules, c.relkind, c.oid, pg_get_expr(d.adbin, d.adrelid), case t.typtype w$
en 'd' then t.typbasetype else 0 end, t.typtypmod, c.relhasoids from (((pg_catalog.pg_class c inner join pg_catalog.pg_namespace n on n.oid = c.relnamespace and c.relname like 'postgres_test_table' and n.nspname like 'public') inne$
 join pg_catalog.pg_attribute a on (not a.attisdropped) and a.attnum > 0 and a.attrelid = c.oid) inner join pg_catalog.pg_type t on t.oid = a.atttypid) left outer join pg_attrdef d on a.atthasdef and d.adrelid = a.attrelid and d.ad$
um = a.attnum order by n.nspname, c.relname, attnum'\n", 738) = 738
```
We're receiving the same info and server/client encoding but in Travis is failing doing 'select oid, typbasetype from pg_type where typname = 'lo'` and instead of this:
```
write(24, "    [ fetched 0 rows ]\n", 23) = 23
write(24, "    [ Large Object oid = -999 ]\n", 32) = 32
write(24, "    [ Client encoding = 'UTF8' (code = 6) ]\n", 44) = 44
write(24, "conn=0x55cecb52eb70, PGAPI_DriverConnect(out)='DRIVER=PostgreSQL Unicode;DATABASE=fdw_tests;SERVER=localhost;PORT=5432;UID=postgres;PWD=;SSLmode=disable;ReadOnly=0;Protocol=7.4;FakeOidIndex=0;ShowOidColumn=0;RowVersionin$
=0;ShowSystemTables=0;ConnSettings=;Fetch=100;Socket=4096;UnknownSizes=0;MaxVarcharSize=255;MaxLongVarcharSize=8190;Debug=0;CommLog=1;Optimizer=0;Ksqo=1;UseDeclareFetch=0;TextAsLongVarchar=1;UnknownsAsLongVarchar=0;BoolsAsChar=0;Pa$
se=0;CancelAsFreeStmt=0;ExtraSysTablePrefixes=dd_;;LFConversion=0;UpdatableCursors=1;DisallowPremature=0;TrueIsMinus1=0;BI=0;ByteaAsLongVarBinary=1;UseServerSidePrepare=1;LowerCaseIdentifier=0;'\n", 648) = 648
write(24, "conn=0x55cecb52eb70, query='select n.nspname, c.relname, a.attname, a.atttypid, t.typname, a.attnum, a.attlen, a.atttypmod, a.attnotnull, c.relhasrules, c.relkind, c.oid, pg_get_expr(d.adbin, d.adrelid), case t.typtype w$
en 'd' then t.typbasetype else 0 end, t.typtypmod, c.relhasoids from (((pg_catalog.pg_class c inner join pg_catalog.pg_namespace n on n.oid = c.relnamespace and c.relname like 'postgres_test_table' and n.nspname like 'public') inne$
 join pg_catalog.pg_attribute a on (not a.attisdropped) and a.attnum > 0 and a.attrelid = c.oid) inner join pg_catalog.pg_type t on t.oid = a.atttypid) left outer join pg_attrdef d on a.atthasdef and d.adrelid = a.attrelid and d.ad$
um = a.attnum order by n.nspname, c.relname, attnum'\n", 738) = 738
sendto(32, "Q\0\0\2\311select n.nspname, c.relname, a.attname, a.atttypid, t.typname, a.attnum, a.attlen, a.atttypmod, a.attnotnull, c.relhasrules, c.relkind, c.oid, pg_get_expr(d.adbin, d.adrelid), case t.typtype when 'd' then t.t$
pbasetype else 0 end, t.typtypmod, c.relhasoids from (((pg_catalog.pg_class c inner join pg_catalog.pg_namespace n on n.oid = c.relnamespace and c.relname like 'postgres_test_table' and n.nspname like 'public') inner join pg_catalo$
.pg_attribute a on (not a.attisdropped) and a.attnum > 0 and a.attrelid = c.oid) inner join pg_catalog.pg_type t on t.oid = a.atttypid) left outer join pg_attrdef d on a.atthasdef and d.adrelid = a.attrelid and d.adnum = a.attnum o$
der by n.nspname, c.relname, attnum\0", 714, MSG_NOSIGNAL, NULL, 0) = 714
```

we're getting the encoding error.

Postgres is the same version 9.5.10 but the machine is not the same. I'll try to use trusty for the local tests. Another thing I notice is that even though we're saying to use the `PostgreSQL Unicode` driver, is using the ANSI one:

```read(32, "[PostgreSQL ANSI]\nDescription = PostgreSQL ODBC driver (ANSI version)\nDriver      = psqlodbca.so\nSetup       = libodbcpsqlS.so\nDebug       = 1\nCommLog     = 1\nUsageCount  = 1\n[PostgreSQL Unicode]\nDescription = Post
greSQL ODBC driver (Unicode version)\nDriver      = psqlodbcw.so\nSetup       = libodbcpsqlS.so\nDebug       = 0\nCommLog     = 1\nUsageCount  = 1\n", 4096) = 356
```

**Comment by ethervoid** [comment] 2018-02-07 17:11
I managed to reproduce the problem in my local environment using a Trusty virtual machine and installing the postgresql using [this ppa](https://www.ubuntuupdates.org/ppa/postgresql?dist=trusty-pgdg)

So the problem seems to be either the postgresql version or the odbc packges. Next step is to use gdb to find what encoding name are we passing

**Comment by ethervoid** [comment] 2018-02-08 10:15
Ok I finally found the culprit. Travis is using the above mentioned ppa which is using the version 10 of `odbc-postgresql` and for some reason that version is not compatible with our code for 9.5. I've fixed the `.travis.yml` and use the 9 version and now is working without a problem.

Also with all of this I've found that in case of error we're in some way keeping the connection open and that's why if we get the encoding error and we retry the query get stucked.

So:

- I'm going to go deep with the incompatibility to see if its a psqlodbc bug and report it
- Find where are we keeping the connection open in case of error and clean it

In the last build all the tests are working except SQL server which seems to be down and I'm asking to the infrastructure people to start it again

**Comment by ethervoid** [comment] 2018-02-08 12:45
For SQL server:

We're using the FreeTDS version 1.x and Trusty is installing version 0.9.x which is not compatible. I tried to use [this package](https://launchpad.net/~jamiewillis/+archive/ubuntu/freetds?field.series_filter=trusty , before compiling our own package) for Trusty, but that package doesn't have the drivers is seems to be only the dev package.

So right now I'm packaging the last stable version of FreeTDS to give it a try in my local environment and if it works, I'll upload it to launchpad to be used in Travis.

Also I'll add the version compatibility/incompatibility to our README

**Comment by pramsey** [comment] 2018-02-08 19:20
@rafatower Should we just move master up to PgSQLv10 for testing purposes, since that's where the ball is going anyways?

**Comment by ethervoid** [comment] 2018-02-09 08:53
Ok, with the last changes the build is again in 💚 . I've added specific documentation about the driver requirements to be clear what we're supporting

Take a look and if it's fine you are more than welcome to merge it

**Comment by rafatower** [comment] 2018-02-09 09:14
@ethervoid thanks a lot for all the help put there :heart:

**Comment by pramsey** [comment] 2018-02-09 22:23
This now seems good and we're merged to master w/ a version matrix.

**Comment by Algunenano** [comment] 2018-02-14 08:52
It seems to be broken again:
```
$ openssl aes-256-cbc -K $encrypted_d52b986e6313_key -iv $encrypted_d52b986e6313_iv -in $TRAVIS_BUILD_DIR/test/config/hive.config.enc -out $TRAVIS_BUILD_DIR/test/config/hive.config -d
iv undefined
The command "openssl aes-256-cbc -K $encrypted_d52b986e6313_key -iv $encrypted_d52b986e6313_iv -in $TRAVIS_BUILD_DIR/test/config/hive.config.enc -out $TRAVIS_BUILD_DIR/test/config/hive.config -d" failed and exited with 1 during .
```

**Comment by ethervoid** [comment] 2018-02-14 08:54
I'm going to check something about the iv

**Comment by ethervoid** [comment] 2018-02-14 09:04
I've asked Travis for support in order to shed some light on this problem because it seems to be some kind of problem. I'll keep you posted

**Comment by Algunenano** [comment] 2018-02-14 09:35
From https://github.com/CartoDB/odbc_fdw/pull/72#issuecomment-365541486: the CI doesn't work with forks.

**Closed by Algunenano** 2018-02-14 09:35 UTC
Labels: bug
